name: build

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        python: ["3.8", "3.10"]
        realsense: ["2.53.1"]
  
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/arm64, linux/amd64
          build-args: |
            PYTHON_VERSION=${{ matrix.python }}
            REALSENSE_VERSION=${{ matrix.realsense }}
          tags: nixone/pyrealsense2:python${{ matrix.python }}-realsense${{ matrix.realsense }}
