name: build

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        opts: |
          ["focal", "3.8", "2.53.1"]
          ["jammy", "3.10", "2.53.1"]
  
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/arm64, linux/amd64
          build-args: |
            UBUNTU_VERSION=${{ matrix.opts[0] }}
            PYTHON_VERSION=${{ matrix.opts[1] }}
            REALSENSE_VERSION=${{ matrix.opts[2] }}
          tags: nixone/pyrealsense2:${{ matrix.opts[0] }}python${{ matrix.opts[1] }}-realsense${{ matrix.opts[2] }}
