name: l4t_based

on:
  workflow_dispatch:

jobs:
  build:
    runs-on:
      - self-hosted
      - arm64

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
      - uses: actions/checkout@v2
        
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.l4t
          push: true
          tags: nixone/pyrealsense2:l4t
