name: l4t_based_rsusb_backend

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.5.1
    
      - uses: actions/checkout@v2
    
      - name: Clean buildx
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.l4t-rsusb-backend
          platforms: linux/arm64/v8
          push: true
          tags: nixone/pyrealsense2:l4t-rsusb-backend
