name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.5.1
    
      - uses: actions/checkout@v2

      - name: Build the docker image
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx build --platform linux/arm64/v8 .
