name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - tag: ubuntu
            file: Dockerfile.ubuntu
          - tag: l4t
            file: Dockerfile.l4t

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.5.1
    
      - uses: actions/checkout@v2
    
      - name: Clean buildx
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ matrix.file }}
          platforms: linux/arm64/v8, linux/amd64
          push: true
          tags: nixone/pyrealsense2:${{ matrix.tag }}
